# Generated by Django 3.0.4 on 2020-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200426_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autority',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
