# Generated by Django 3.0.4 on 2020-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200505_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='adcode',
            field=models.CharField(max_length=10),
        ),
    ]
