# Generated by Django 3.0.4 on 2020-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200505_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, to='login.Region'),
        ),
    ]
