# Generated by Django 3.0.4 on 2020-03-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=30)),
                ('provinceId', models.IntegerField()),
                ('provinceTotal', models.IntegerField()),
                ('cityName', models.CharField(max_length=30)),
                ('cityId', models.IntegerField()),
                ('cityLon', models.FloatField()),
                ('cityLat', models.FloatField()),
                ('cityLevel', models.IntegerField()),
                ('cityCount', models.IntegerField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('changedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiName', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('tag', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=30)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('changedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
