# Generated by Django 3.0.4 on 2020-06-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['cityId'], 'verbose_name': '地区', 'verbose_name_plural': '地区'},
        ),
        migrations.AlterModelOptions(
            name='pois',
            options={'verbose_name': '疫情点', 'verbose_name_plural': '疫情点'},
        ),
    ]
